version: '3.8'

services:
  # Hauptwebserver für Nextcloud
  nextcloud:
    image: nextcloud:latest
    restart: always
    ports:
      - "8080:80"
    volumes:
      - nextcloud_data:/var/www/html
      - ./apps:/var/www/html/custom_apps
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=db
      - TRUSTED_PROXIES=reverse-proxy
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost,swissairdry.com
    depends_on:
      - db
    networks:
      - frontend
      - backend

  # Datenbank für Nextcloud
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend

  # Reverse Proxy für SSL-Terminierung und Routing
  reverse-proxy:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - nextcloud
      - swissairdry-api
      - swissairdry-exapp
    networks:
      - frontend

  # SwissAirDry API-Server
  swissairdry-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - DATABASE_URL=postgresql://swissairdry:swissairdry@postgres:5432/swissairdry
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=swissairdry
      - LOG_LEVEL=INFO
    depends_on:
      - postgres
      - mqtt-broker
    networks:
      - backend
      - mqtt-net

  # SwissAirDry Simple API für einfachere Gerätesteuerung
  swissairdry-simple-api:
    build:
      context: ./api
      dockerfile: Dockerfile.simple
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - ./api:/app
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=swissairdry
      - LOG_LEVEL=INFO
    depends_on:
      - mqtt-broker
    networks:
      - backend
      - mqtt-net

  # SwissAirDry ExApp Server
  swissairdry-exapp:
    build:
      context: ./swissairdry-exapp
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./swissairdry-exapp:/app
    environment:
      - API_URL=http://swissairdry-api:5000
      - NEXTCLOUD_URL=http://nextcloud:80
      - NODE_ENV=production
    depends_on:
      - swissairdry-api
    networks:
      - frontend
      - backend

  # SwissAirDry ExApp Daemon
  swissairdry-exapp-daemon:
    build:
      context: ./swissairdry-exapp/daemon
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8701:8701"
    volumes:
      - ./swissairdry-exapp/daemon:/app
    environment:
      - MQTT_BROKER=mqtt-broker
      - MQTT_PORT=1883
      - MQTT_TOPIC_PREFIX=swissairdry
      - LOG_LEVEL=INFO
      - NEXTCLOUD_URL=http://nextcloud:80
    depends_on:
      - mqtt-broker
      - nextcloud
    networks:
      - backend
      - mqtt-net

  # MQTT-Broker
  mqtt-broker:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    networks:
      - mqtt-net

  # PostgreSQL-Datenbank für SwissAirDry
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=swissairdry
      - POSTGRES_PASSWORD=swissairdry
      - POSTGRES_DB=swissairdry
    networks:
      - backend

volumes:
  nextcloud_data:
  db_data:
  mqtt_data:
  mqtt_log:
  postgres_data:

networks:
  frontend:
  backend:
  mqtt-net: