version: '3.8'

services:
  # Portainer - Container-Management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: swissairdry-portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    ports:
      - "${PORTAINER_PORT:-9000}:9000"
    networks:
      - swissairdry-network

  # PostgreSQL Datenbank
  db:
    image: postgres:14-alpine
    container_name: swissairdry-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-swissairdry}
      POSTGRES_DB: ${DB_NAME:-swissairdry}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - swissairdry-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: swissairdry-mqtt
    restart: unless-stopped
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "${MQTT_WS_PORT:-9001}:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt-data:/mosquitto/data
      - mqtt-log:/mosquitto/log
    networks:
      - swissairdry-network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - MQTT_ALLOW_ANONYMOUS=${MQTT_ALLOW_ANONYMOUS:-true}
      - MQTT_SSL_ENABLED=${MQTT_SSL_ENABLED:-false}
      - MQTT_AUTH_ENABLED=${MQTT_AUTH_ENABLED:-false}
  
  # Main API (FastAPI)
  api:
    image: ${REGISTRY_URL:-ghcr.io/arduinoeinsteiger}/swissairdry-api:${IMAGE_TAG:-latest}
    build:
      context: ./api
      dockerfile: Dockerfile.api
    container_name: swissairdry-api
    restart: unless-stopped
    ports:
      - "${API_PORT:-5000}:5000"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5000
      - DB_HOST=db
      - MQTT_BROKER=mqtt
      - NEXTCLOUD_URL=http://nextcloud:8080
    volumes:
      - ./api:/app
      - api-logs:/app/logs
    networks:
      - swissairdry-network
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Simple API (Flask)
  simple-api:
    image: ${REGISTRY_URL:-ghcr.io/arduinoeinsteiger}/swissairdry-simple-api:${IMAGE_TAG:-latest}
    build:
      context: ./api
      dockerfile: Dockerfile.simple
    container_name: swissairdry-simple-api
    restart: unless-stopped
    ports:
      - "${SIMPLE_API_PORT:-5001}:5001"
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5001
      - MQTT_BROKER=mqtt
      - MQTT_CLIENT_ID=${MQTT_SIMPLE_CLIENT_ID:-swissairdry-simple-api}
    volumes:
      - ./api:/app
      - simple-api-logs:/app/logs
    networks:
      - swissairdry-network
    depends_on:
      mqtt:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nextcloud Container
  nextcloud:
    image: nextcloud:26-fpm-alpine
    container_name: swissairdry-nextcloud
    restart: unless-stopped
    volumes:
      - nextcloud-data:/var/www/html
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/custom_apps:/var/www/html/custom_apps
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${NEXTCLOUD_DB_NAME:-nextcloud}
      - POSTGRES_USER=${NEXTCLOUD_DB_USER:-nextcloud}
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD:-nextcloud}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS:-nextcloud localhost}
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=1G
    networks:
      - swissairdry-network
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "php -f /var/www/html/occ status | grep -q 'installed: true'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
        
  # ExApp (Nextcloud App)
  exapp:
    image: ${REGISTRY_URL:-ghcr.io/arduinoeinsteiger}/swissairdry-exapp:${IMAGE_TAG:-latest}
    build:
      context: ./nextcloud
      dockerfile: Dockerfile.exapp
    container_name: swissairdry-exapp
    restart: unless-stopped
    ports:
      - "${EXAPP_PORT:-8080}:8080"
    env_file:
      - .env
    environment:
      - API_URL=http://api:${API_PORT:-5000}
      - SIMPLE_API_URL=http://simple-api:${SIMPLE_API_PORT:-5001}
      - NEXTCLOUD_URL=http://nextcloud:8080
    volumes:
      - ./nextcloud:/app
      - exapp-logs:/app/logs
    networks:
      - swissairdry-network
    depends_on:
      api:
        condition: service_healthy
      simple-api:
        condition: service_healthy
      nextcloud:
        condition: service_healthy
        
  # ExApp Daemon (Brücke zwischen Nextcloud und SwissAirDry API)
  exapp-daemon:
    image: ${REGISTRY_URL:-ghcr.io/arduinoeinsteiger}/swissairdry-exapp-daemon:${IMAGE_TAG:-latest}
    build:
      context: ./nextcloud
      dockerfile: Dockerfile.daemon
    container_name: swissairdry-exapp-daemon
    restart: unless-stopped
    ports:
      - "${EXAPP_DAEMON_PORT:-8081}:8081"
    env_file:
      - .env
    environment:
      - APP_ID=swissairdry
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - APP_SECRET=${EXAPP_SECRET_KEY:-changeme_in_production}
      - NEXTCLOUD_URL=${NEXTCLOUD_URL:-http://nextcloud:8080}
      - NEXTCLOUD_USER=${NEXTCLOUD_ADMIN_USER:-admin}
      - NEXTCLOUD_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD:-admin}
      - API_URL=http://api:${API_PORT:-5000}
      - SIMPLE_API_URL=http://simple-api:${SIMPLE_API_PORT:-5001}
      - MQTT_BROKER=mqtt
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_WS_PORT=${MQTT_WS_PORT:-9001}
      - MQTT_USERNAME=${MQTT_USERNAME:-}
      - MQTT_PASSWORD=${MQTT_PASSWORD:-}
      - DB_HOST=db
    volumes:
      - ./nextcloud:/app
      - exapp-daemon-logs:/app/logs
    networks:
      - swissairdry-network
    depends_on:
      - mqtt
      - api
      - simple-api
      - nextcloud
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/status"]
      interval: 30s
      timeout: 10s
      retries: 3
  
  # Nginx Web Server für Nextcloud und API
  nginx:
    image: nginx:alpine
    container_name: swissairdry-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - nextcloud-data:/var/www/html:ro
    networks:
      - swissairdry-network
    depends_on:
      - nextcloud
      - api
      - simple-api
      - exapp
      - exapp-daemon

networks:
  swissairdry-network:
    driver: bridge

volumes:
  db-data:
  mqtt-data:
  mqtt-log:
  api-logs:
  simple-api-logs:
  exapp-logs:
  exapp-daemon-logs:
  nextcloud-data:
  portainer-data: